'use client'

import { useState } from 'react'
import { FileBarChart, Copy, Send, Loader2, ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'

// ---- Report generators ----

function generateMonthlyReport(data: any): string {
  const now = new Date()
  const monthName = now.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })

  let report = `📊 OUTLANDER MAGAZINE — ${monthName.toUpperCase()} SUMMARY\n\n`

  if (data?.billingTracker) {
    report += `💰 Booked Revenue YTD: ${data.billingTracker.bookedRevenue || '—'}\n`
    report += `📊 Gap to Target: ${data.billingTracker.gapToTarget || '—'}\n`
    report += `📋 Total Deals: ${data.billingTracker.totalDeals || 0}\n`
  }

  if (data?.xero?.connected !== false && data?.xero) {
    report += `\n🏦 XERO FINANCIALS\n`
    report += `Income: £${data.xero.totalIncome?.toLocaleString() || '0'}\n`
    report += `Expenses: £${data.xero.totalExpenses?.toLocaleString() || '0'}\n`
    report += `Net Profit: £${data.xero.netProfit?.toLocaleString() || '0'}\n`
    report += `Bank Balance: £${data.xero.bankBalance?.toLocaleString() || '0'}\n`
  }

  if (data?.xero?.invoices?.length) {
    const outstanding = data.xero.invoices.filter((inv: any) => inv.status === 'AUTHORISED' || inv.status === 'OVERDUE')
    report += `\n📬 OUTSTANDING INVOICES: ${outstanding.length}\n`
    const total = outstanding.reduce((s: number, inv: any) => s + (inv.amountDue || 0), 0)
    report += `Total Outstanding: £${total.toLocaleString()}\n`
  }

  report += `\n— Generated by OutlanderOS`
  return report
}

function generateQuarterlyReport(data: any): string {
  const now = new Date()
  const year = now.getFullYear()
  const q = Math.ceil((now.getMonth() + 1) / 3)

  let report = `📊 OUTLANDER MAGAZINE — ${year} QUARTERLY REVIEW\n\n`
  report += `Current Quarter: Q${q} ${year}\n\n`

  if (data?.billingTracker) {
    report += `YTD BILLING\n`
    report += `Booked Revenue: ${data.billingTracker.bookedRevenue || '—'}\n`
    report += `Gap to Target: ${data.billingTracker.gapToTarget || '—'}\n`
    report += `Total Deals: ${data.billingTracker.totalDeals || 0}\n`

    const deals = data.billingTracker.deals || []
    if (deals.length) {
      const signed = deals.filter((d: any) => d.signed).length
      report += `Signed: ${signed} / ${deals.length}\n`
    }
  }

  if (data?.xero) {
    report += `\nFINANCIALS (YTD)\n`
    report += `Income: £${data.xero.totalIncome?.toLocaleString() || '0'}\n`
    report += `Expenses: £${data.xero.totalExpenses?.toLocaleString() || '0'}\n`
    report += `Net Profit: £${data.xero.netProfit?.toLocaleString() || '0'}\n`
    report += `Bank Balance: £${data.xero.bankBalance?.toLocaleString() || '0'}\n`

    const margin = data.xero.totalIncome
      ? ((data.xero.netProfit / data.xero.totalIncome) * 100).toFixed(1)
      : null
    if (margin) report += `Margin: ${margin}%\n`
  }

  report += `\n— Generated by OutlanderOS`
  return report
}

function generateClientReport(data: any, clientName: string): string {
  if (!clientName) return 'Select a client first.'

  let report = `📊 OUTLANDER MAGAZINE — CLIENT REPORT\n`
  report += `Client: ${clientName}\n`
  report += `Generated: ${new Date().toLocaleDateString('en-GB')}\n\n`

  const deals = data?.billingTracker?.deals?.filter(
    (d: any) => d.client?.toLowerCase().includes(clientName.toLowerCase())
  ) || []

  if (deals.length) {
    report += `DEALS (${deals.length})\n`
    let totalValue = 0
    for (const d of deals) {
      report += `  • ${d.description || d.client} — £${d.value?.toLocaleString() || 0} ${d.signed ? '✓ Signed' : '○ Unsigned'}\n`
      totalValue += d.value || 0
    }
    report += `Total Deal Value: £${totalValue.toLocaleString()}\n\n`
  } else {
    report += `No deals found for this client.\n\n`
  }

  const invoices = data?.xero?.invoices?.filter(
    (inv: any) => inv.contact?.toLowerCase().includes(clientName.toLowerCase())
  ) || []

  if (invoices.length) {
    report += `INVOICES (${invoices.length})\n`
    for (const inv of invoices) {
      report += `  • ${inv.invoiceNumber || inv.id} — £${inv.amountDue?.toLocaleString() || 0} — ${inv.status} — Due: ${inv.dueDate || '—'}\n`
    }
  } else {
    report += `No invoices found for this client.\n`
  }

  report += `\n— Generated by OutlanderOS`
  return report
}

// ---- Component ----

type ReportType = 'monthly' | 'quarterly' | 'client'

export default function ReportsPage() {
  const [preview, setPreview] = useState<string | null>(null)
  const [activeReport, setActiveReport] = useState<ReportType | null>(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [sending, setSending] = useState(false)
  const [sendResult, setSendResult] = useState<string | null>(null)
  const [selectedClient, setSelectedClient] = useState('')
  const [clientList, setClientList] = useState<string[]>([])

  async function fetchAndGenerate(type: ReportType) {
    setLoading(true)
    setPreview(null)
    setSendResult(null)
    try {
      const res = await fetch('/api/dashboard')
      const data = await res.json()

      // Build client list for dropdown
      const clients = new Set<string>()
      for (const d of data?.billingTracker?.deals || []) {
        if (d.client) clients.add(d.client)
      }
      for (const inv of data?.xero?.invoices || []) {
        if (inv.contact) clients.add(inv.contact)
      }
      setClientList(Array.from(clients).sort())

      let report = ''
      if (type === 'monthly') report = generateMonthlyReport(data)
      else if (type === 'quarterly') report = generateQuarterlyReport(data)
      else if (type === 'client') report = generateClientReport(data, selectedClient)

      setPreview(report)
      setActiveReport(type)
    } finally {
      setLoading(false)
    }
  }

  async function copyToClipboard() {
    if (!preview) return
    await navigator.clipboard.writeText(preview)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function sendToTelegram() {
    if (!preview) return
    setSending(true)
    setSendResult(null)
    try {
      const res = await fetch('/api/telegram/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: preview }),
      })
      const json = await res.json()
      setSendResult(json.ok ? 'Sent to Telegram.' : 'Failed to send.')
    } catch {
      setSendResult('Error sending to Telegram.')
    } finally {
      setSending(false)
    }
  }

  const cards = [
    {
      type: 'monthly' as const,
      title: 'Monthly Summary Report',
      description: 'Revenue, deals, invoices, payments, and outstanding balances for this month.',
    },
    {
      type: 'quarterly' as const,
      title: 'Quarterly Review',
      description: 'Aggregated Q1–Q4 breakdown with year-to-date totals.',
    },
    {
      type: 'client' as const,
      title: 'Client Report',
      description: 'Deal value, invoice status, and payment history for one client.',
    },
  ]

  return (
    <div className="space-y-6 px-1">
      {/* Header */}
      <div>
        <h1 className="text-xl font-semibold text-gray-900">Reports</h1>
        <p className="text-sm text-gray-500">Generate and share business reports</p>
      </div>

      {/* Report cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {cards.map(card => (
          <div
            key={card.type}
            className={cn(
              'rounded-xl border bg-white p-4 space-y-3 transition-colors',
              activeReport === card.type ? 'border-[#D4A853]' : 'border-gray-200'
            )}
          >
            <div className="flex items-start gap-2">
              <FileBarChart className="mt-0.5 h-4 w-4 shrink-0 text-[#D4A853]" />
              <div>
                <p className="text-sm font-semibold text-gray-900">{card.title}</p>
                <p className="mt-0.5 text-xs text-gray-500">{card.description}</p>
              </div>
            </div>

            {card.type === 'client' && (
              <div className="relative">
                <select
                  value={selectedClient}
                  onChange={e => setSelectedClient(e.target.value)}
                  className="w-full appearance-none rounded-lg border border-gray-200 bg-gray-50 py-1.5 pl-3 pr-8 text-xs text-gray-700 focus:border-[#D4A853] focus:outline-none"
                >
                  <option value="">Select client…</option>
                  {clientList.map(c => (
                    <option key={c} value={c}>{c}</option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute right-2 top-2 h-3.5 w-3.5 text-gray-400" />
              </div>
            )}

            <button
              onClick={() => fetchAndGenerate(card.type)}
              disabled={loading || (card.type === 'client' && !selectedClient)}
              className={cn(
                'w-full rounded-lg py-1.5 text-xs font-medium transition-colors',
                'bg-[#D4A853] text-gray-900 hover:bg-[#c49a47]',
                'disabled:opacity-40 disabled:cursor-not-allowed'
              )}
            >
              {loading && activeReport === card.type ? (
                <span className="flex items-center justify-center gap-1.5">
                  <Loader2 className="h-3 w-3 animate-spin" /> Generating…
                </span>
              ) : (
                'Generate'
              )}
            </button>
          </div>
        ))}
      </div>

      {/* Preview panel */}
      {preview && (
        <div className="rounded-xl border border-gray-200 bg-white overflow-hidden">
          <div className="flex items-center justify-between border-b border-gray-200 px-4 py-3">
            <span className="text-sm font-semibold text-gray-800">Preview</span>
            <div className="flex items-center gap-2">
              {sendResult && (
                <span className="text-xs text-gray-500">{sendResult}</span>
              )}
              <button
                onClick={sendToTelegram}
                disabled={sending}
                className="flex items-center gap-1.5 rounded-lg border border-gray-200 px-3 py-1.5 text-xs text-gray-600 hover:bg-gray-100 transition-colors disabled:opacity-40"
              >
                {sending ? <Loader2 className="h-3 w-3 animate-spin" /> : <Send className="h-3 w-3" />}
                Send to Telegram
              </button>
              <button
                onClick={copyToClipboard}
                className="flex items-center gap-1.5 rounded-lg border border-gray-200 px-3 py-1.5 text-xs text-gray-600 hover:bg-gray-100 transition-colors"
              >
                <Copy className="h-3 w-3" />
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>
          <pre className="whitespace-pre-wrap px-5 py-4 text-xs leading-relaxed text-gray-700 font-mono">
            {preview}
          </pre>
        </div>
      )}
    </div>
  )
}
